name: Waka Readme

on:
  workflow_dispatch:
  schedule:
  # Runs every hour
    - cron: "30 * * * *"
    
jobs:
  update-readme:
    name: Waka - Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: update dev stats 
          SHOW_TOTAL: true
